# Generated by Django 2.1.15 on 2022-05-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo_items',
            fields=[
                ('td_id', models.AutoField(primary_key=True, serialize=False)),
                ('todo_work', models.CharField(max_length=500)),
            ],
        ),
    ]
