# Generated by Django 2.1.15 on 2022-05-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_items',
            name='todo_work',
        ),
        migrations.AddField(
            model_name='todo_items',
            name='todo_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='todo_items',
            name='todo_isdone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo_items',
            name='todo_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
