# Generated by Django 2.1.15 on 2022-05-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220523_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_items',
            name='todo_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='todo_items',
            name='todo_title',
            field=models.CharField(max_length=100),
        ),
    ]
